# AI Model Configuration - Claude Only
models:
  anthropic:
    claude-3-haiku-20240307:
      model_name: "claude-3-haiku-20240307"
      temperature: 0.1
      max_tokens: 2048
      system_prompt: "You are a helpful legal assistant."

  embeddings:
    sentence-transformers:
      model_name: "all-MiniLM-L6-v2"
      dimensions: 384
      max_tokens: 256

# Legal Analysis Prompts
prompts:
  case_analysis:
    system: |
      You are an expert legal analyst with deep knowledge of case law and legal precedents.
      Analyze the provided case facts and identify relevant legal issues, potential defenses,
      and applicable precedents. Provide structured, professional legal analysis.
    
    user_template: |
      Case Facts: {case_facts}
      Jurisdiction: {jurisdiction}
      Case Type: {case_type}
      
      Please provide a comprehensive legal analysis including:
      1. Key legal issues
      2. Potential defenses
      3. Relevant precedents
      4. Risk assessment
      5. Recommended strategy

  defense_generation:
    system: |
      You are a skilled defense attorney with expertise in crafting legal arguments.
      Generate comprehensive defense strategies based on case facts and precedents.
      Focus on practical, legally sound arguments that can be presented in court.
    
    user_template: |
      Case Facts: {case_facts}
      Similar Cases: {similar_cases}
      Jurisdiction: {jurisdiction}
      
      Generate a defense strategy including:
      1. Primary defense arguments
      2. Supporting evidence requirements
      3. Witness strategy
      4. Cross-examination points
      5. Closing argument framework

  precedent_analysis:
    system: |
      You are a legal researcher specializing in case law analysis.
      Analyze legal precedents and extract key legal principles, holdings, and reasoning.
      Focus on applicability to current cases.
    
    user_template: |
      Precedent Case: {case_name}
      Case Text: {case_text}
      
      Extract and analyze:
      1. Key legal principles
      2. Court's reasoning
      3. Applicable holdings
      4. Distinguishing factors
      5. Relevance to similar cases

  document_summarization:
    system: |
      You are a legal document analyst. Provide clear, concise summaries of legal documents
      focusing on the most important legal principles and practical implications.
    
    user_template: |
      Document Text: {document_text}
      
      Please provide a comprehensive summary including:
      1. Key facts and issues
      2. Legal principles involved
      3. Court's decision
      4. Important reasoning
      5. Practical implications

# Model Selection Rules
model_selection:
  case_analysis: "claude-3-haiku-20240307"
  defense_generation: "claude-3-haiku-20240307"
  precedent_analysis: "claude-3-haiku-20240307"
  document_summarization: "claude-3-haiku-20240307"
  similarity_matching: "sentence-transformers"

# Performance Settings
performance:
  batch_size: 10
  max_concurrent_requests: 5
  timeout_seconds: 30
  retry_attempts: 3
  cache_duration_hours: 24 